#!/usr/bin/env bash
# Build a portable AppImage for mtools_gui.
#
# PySide6 is pinned here to the last release built against
# manylinux_2_28 (glibc >= 2.28 - Ubuntu 18.10+/20.04/22.04, Debian 10+,
# Fedora 29+, etc.), NOT the unbounded ">=6.6" from pyproject.toml:
# PySide6 6.10+ switched to manylinux_2_34, which would make the
# resulting AppImage require a much newer host glibc and defeat the
# point of a portable, distro-agnostic package. Re-check this pin
# whenever bumping PySide6 (see the version-tag survey in the project's
# packaging notes/plan history if it needs redoing).
#
# Usage: packaging/appimage/build.sh
# Output: mtools_gui-x86_64.AppImage in the repo root.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
PYSIDE6_PIN="PySide6==6.9.3"
PYTHON_VERSION="3.12"

cd "$ROOT"

# The build extracts a base Python AppImage and installs PySide6 (Qt is
# large) into it - easily several hundred MB. Default /tmp is often a
# small tmpfs (RAM-backed) on desktop systems, which can fail with
# ENOSPC well before the disk itself is full. Use a directory under the
# repo instead, which sits on regular disk.
export TMPDIR="$ROOT/.appimage-build-tmp"
mkdir -p "$TMPDIR"
trap 'rm -rf "$TMPDIR"' EXIT

echo "==> Setting up an isolated build venv"
python3 -m venv .appimage-build-venv
.appimage-build-venv/bin/pip install --quiet --upgrade pip build python-appimage

echo "==> Building the mtools_gui wheel"
rm -rf dist
.appimage-build-venv/bin/python -m build --wheel --outdir dist
WHEEL="$(ls "$ROOT"/dist/mtools_gui-*.whl | head -1)"
echo "    $WHEEL"

echo "==> Writing recipe requirements.txt"
cat > "$HERE/requirements.txt" <<EOF
# Generated by build.sh - do not edit by hand, edit build.sh instead.
$PYSIDE6_PIN
$WHEEL
EOF

echo "==> Running python-appimage"
.appimage-build-venv/bin/python-appimage build app -p "$PYTHON_VERSION" "$HERE"

echo "==> Done - AppImage written to $ROOT"
